package com.codedbykay.purenotes.models

enum class SortOrder {
    CREATED_AT_ASCENDING,
    CREATED_AT_DESCENDING,
    NOTIFICATION_TIME_ASCENDING,
    NOTIFICATION_TIME_DESCENDING,
    TITLE_ASCENDING,
    TITLE_DESCENDING
}