workflows:
  android-workflow:
    name: A Pure Notes (Android Build Workflow)
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      groups:
        - pure-notes
        - pure_notes_google_credential

      vars:
        # Path where the keystore will be decoded
        KEYSTORE_DECODING_PATH: "/tmp/keystore/codedbykay-purenotes-keystore.jks"

        # Additional Variables (Ensure these are set in CodeMagic's environment variables)
        # BUILD_TYPE: "release" or "debug" (Set based on your build needs)

    scripts:
      - name: Determine Environment
        script: |
          if [ "$(uname -s)" == "Linux" ]; then
            echo "IS_LINUX_ENV=true" >> $CM_ENV
          else
            echo "IS_LINUX_ENV=false" >> $CM_ENV
          fi

      - name: Set Execute Permission for gradlew
        script: chmod +x ./gradlew

      - name: Decode Keystore File
        script: |
          echo "Decoding the keystore file..."
          mkdir -p /tmp/keystore
          echo $KEYSTORE | base64 --decode > "$KEYSTORE_DECODING_PATH"
          echo "Keystore decoded successfully to $KEYSTORE_DECODING_PATH"

      - name: Run Unit Tests
        script: |
          echo "Running unit tests..."
          ./gradlew test
          echo "Unit tests completed."

      - name: Build APK or AAB
        script: |
          echo "Detected BUILD_TYPE: $BUILD_TYPE"
          if [ "$BUILD_TYPE" = "release" ]; then
            echo "Building release AAB..."
            ./gradlew bundleRelease
            echo "Release AAB built successfully."
          else
            echo "Building debug APK..."
            ./gradlew assembleDebug
            echo "Debug APK built successfully."
          fi

      - name: List Release AABs and APKs
        script: |
          if [ "$BUILD_TYPE" = "release" ]; then
            echo "Listing AABs in app/build/outputs/bundle/release/"
            ls -l app/build/outputs/bundle/release/
          else
            echo "Listing APKs in app/build/outputs/apk/debug/"
            ls -l app/build/outputs/apk/debug/
          fi

      - name: Conditionally Start Emulator
        script: |
          if [ "$IS_LINUX_ENV" = "true" ]; then
            echo "Linux environment detected. Starting Android emulator..."
            emulator -avd Pixel_3_API_30 -no-audio -no-boot-anim -no-window &
            adb wait-for-device
            adb shell input keyevent 82
            echo "Emulator is ready."
          else
            echo "Skipping emulator startup as this is not a Linux environment."
          fi

      - name: Conditionally Run Instrumentation Tests
        script: |
          if [ "$IS_LINUX_ENV" = "true" ]; then
            echo "Running instrumentation tests..."
            ./gradlew connectedAndroidTest --no-daemon
            echo "Instrumentation tests completed."
          else
            echo "Skipping instrumentation tests as this is not a Linux environment."
          fi

    artifacts:
      - app/build/outputs/**/*.aab
      - app/build/outputs/**/*.apk
      - app/build/reports/androidTests/connected/index.html
      - app/build/reports/tests/testDebugUnitTest/index.html

    publishing:
      email:
        recipients:
          - kaywib@gmail.com

      google_play:
        # Contents of the JSON key file for Google Play service account saved
        # as a secure environment variable
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS

        # Name of the track: internal, alpha, beta, production, internal app sharing,
        # or your custom track name
        track: internal
        submit_as_draft: true

        # Optional Priority of the release (only set if in-app updates are supported)
        # integer in range [0, 5]
        # in_app_update_priority: 3

        # Optional. Rollout fraction (set only if releasing to a fraction of users)
        # value between (0, 1)
        # rollout_fraction: 0.25

        # Optional boolean To be used ONLY if your app cannot be sent for review automatically *
        # changes_not_sent_for_review: true
