workflows:
  android-workflow:
    name: A Pure Notes (Android Build Workflow)
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    env-var:
      environment:
        groups:
          - pure-notes
        vars:
          IS_LINUX_ENV: $([ "$(uname -s)" == "Linux" ] && echo "true" || echo "false")
      scripts:
        - name: Check BUILD TYPE
          script: |
            echo "Detected BUILD_TYPE: $BUILD_TYPE"

