workflows:
  android-workflow:
    name: A Pure notes (Android Build Workflow)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
      # Define any environment variables here
    scripts:
      - name: Run Unit Tests
        script: ./gradlew test
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - kaywib@gmail.com
