workflows:
  android-workflow:
    name: A Pure Notes (Android Build Workflow)
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      android:
        components:
          - tools
          - platform-tools
          - build-tools-34.0.0
          - android-34
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set Execute Permission for gradlew
        script: chmod +x ./gradlew
      - name: Run Unit Tests
        script: ./gradlew test
      - name: Build Debug APK
        script: ./gradlew assembleDebug
      - name: Start Emulator
        script: |
          echo "Starting Android emulator..."
          /Users/builder/Library/Android/sdk/emulator/emulator -avd Pixel_3_API_30 -no-audio -no-boot-anim -no-window &
          adb wait-for-device
          adb shell input keyevent 82
          echo "Emulator is ready."
      - name: Run Instrumentation Tests
        script: |
          echo "Running instrumentation tests..."
          ./gradlew connectedAndroidTest --no-daemon
          echo "Instrumentation tests completed."
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/reports/androidTests/connected/index.html
      - app/build/reports/tests/testDebugUnitTest/index.html
    publishing:
      email:
        recipients:
          - kaywib@gmail.com
