workflows:
  android-workflow:
    name: A Pure Notes (Android Build Workflow)
    max_build_duration: 60
    instance_type: mac_mini_m2
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set Execute Permission for gradlew
        script: chmod +x ./gradlew
      - name: Run Unit Tests
        script: ./gradlew test
      - name: Run Android Lint
        script: ./gradlew lint
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/reports/jacoco/test/html
    caching:
      cache_paths:
        - ~/.gradle
    publishing:
      email:
        recipients:
          - kaywib@gmail.com
