package com.codedbykay.purenotes.ui.theme.widget

import androidx.compose.ui.graphics.Color

// Light theme colors - Default
val primaryLightDefault = Color(0xFF212627)
val onPrimaryLightDefault = Color(0xFFFFFFFF)
val primaryContainerLightDefault = Color(0xFF424748)
val onPrimaryContainerLightDefault = Color(0xFFDBDFE0)
val secondaryLightDefault = Color(0xFF5D5E5F)
val onSecondaryLightDefault = Color(0xFFFFFFFF)
val secondaryContainerLightDefault = Color(0xFFE6E6E6)
val onSecondaryContainerLightDefault = Color(0xFF494A4B)
val tertiaryLightDefault = Color(0xFF272429)
val onTertiaryLightDefault = Color(0xFFFFFFFF)
val tertiaryContainerLightDefault = Color(0xFF48454A)
val onTertiaryContainerLightDefault = Color(0xFFE3DDE3)
val errorLightDefault = Color(0xFFBA1A1A)
val onErrorLightDefault = Color(0xFFFFFFFF)
val errorContainerLightDefault = Color(0xFFFFDAD6)
val onErrorContainerLightDefault = Color(0xFF410002)
val backgroundLightDefault = Color(0xFFFCF9F8)
val onBackgroundLightDefault = Color(0xFF1C1B1B)
val surfaceLightDefault = Color(0xFFFCF9F8)
val onSurfaceLightDefault = Color(0xFF1C1B1B)
val surfaceVariantLightDefault = Color(0x80E0E3E4)
val onSurfaceVariantLightDefault = Color(0xFF434748)
val outlineLightDefault = Color(0xFF747879)
val outlineVariantLightDefault = Color(0xFFC3C7C8)
val scrimLightDefault = Color(0xFF000000)
val inverseSurfaceLightDefault = Color(0xFF313030)
val inverseOnSurfaceLightDefault = Color(0xFFF3F0EF)
val inversePrimaryLightDefault = Color(0xFFC3C7C8)
val surfaceDimLightDefault = Color(0xFFDCD9D9)
val surfaceBrightLightDefault = Color(0xFFFCF9F8)
val surfaceContainerLowestLightDefault = Color(0xFFFFFFFF)
val surfaceContainerLowLightDefault = Color(0xFFF6F3F2)
val surfaceContainerLightDefault = Color(0xFFF0EDEC)
val surfaceContainerHighLightDefault = Color(0xFFEBE7E7)
val surfaceContainerHighestLightDefault = Color(0xFFE5E2E1)

// Dark theme colors - Default
val primaryDarkDefault = Color(0xFFC3C7C8)
val onPrimaryDarkDefault = Color(0xFF2C3132)
val primaryContainerDarkDefault = Color(0xFF2A2F30)
val onPrimaryContainerDarkDefault = Color(0xFFB8BCBD)
val secondaryDarkDefault = Color(0xFFC6C6C6)
val onSecondaryDarkDefault = Color(0xFF2F3131)
val secondaryContainerDarkDefault = Color(0xFF3C3D3D)
val onSecondaryContainerDarkDefault = Color(0xFFD0D0D0)
val tertiaryDarkDefault = Color(0xFFCBC5CB)
val onTertiaryDarkDefault = Color(0xFF322F34)
val tertiaryContainerDarkDefault = Color(0xFF302D32)
val onTertiaryContainerDarkDefault = Color(0xFFBFB9C0)
val errorDarkDefault = Color(0xFFFFB4AB)
val onErrorDarkDefault = Color(0xFF690005)
val errorContainerDarkDefault = Color(0xFF93000A)
val onErrorContainerDarkDefault = Color(0xFFFFDAD6)
val backgroundDarkDefault = Color(0xFF131313)
val onBackgroundDarkDefault = Color(0xFFE5E2E1)
val surfaceDarkDefault = Color(0xFF131313)
val onSurfaceDarkDefault = Color(0xFFE5E2E1)
val surfaceVariantDarkDefault = Color(0x80434748)
val onSurfaceVariantDarkDefault = Color(0xFFC3C7C8)
val outlineDarkDefault = Color(0xFF8D9192)
val outlineVariantDarkDefault = Color(0xFF434748)
val scrimDarkDefault = Color(0xFF000000)
val inverseSurfaceDarkDefault = Color(0xFFE5E2E1)
val inverseOnSurfaceDarkDefault = Color(0xFF313030)
val inversePrimaryDarkDefault = Color(0xFF5A5F60)
val surfaceDimDarkDefault = Color(0xFF131313)
val surfaceBrightDarkDefault = Color(0xFF3A3939)
val surfaceContainerLowestDarkDefault = Color(0xFF0E0E0E)
val surfaceContainerLowDarkDefault = Color(0xFF1C1B1B)
val surfaceContainerDarkDefault = Color(0xFF201F1F)
val surfaceContainerHighDarkDefault = Color(0xFF2A2A2A)
val surfaceContainerHighestDarkDefault = Color(0xFF353534)
